# inventory/hosts.yaml
core:
  hostname: core
  platform: arista
  groups: [switch]
  
access1:
  hostname: access1
  platform: arista
  groups: [switch]

access2:
  hostname: access2
  platform: arista
  groups: [switch]
